"""
SQL Query Tool.
Uses Gemini to convert a natural language question into a SQL query,
executes it against the in-memory database, and returns structured results.
"""

import logging
import re
import sqlite3
from typing import Any

from google import genai

from database import execute_query

logger = logging.getLogger(__name__)


SCHEMA_DESCRIPTION = """
Database tables and columns:

sectors(sector_id PK, sector_name, sector_description, industry_group)

securities(security_id PK, symbol, company_name, asset_type IN ('Stock','Bond'),
           sector_id FK->sectors, market_cap, current_price, currency, exchange,
           country, listing_date, maturity_date, coupon_rate)

benchmarks(benchmark_id PK, benchmark_name, benchmark_symbol, benchmark_type,
           description, inception_date)

portfolios(portfolio_id PK, portfolio_name, creation_date, target_risk_level,
           total_aum, strategy_type, benchmark_index, status)

holdings(holding_id PK, portfolio_id FK->portfolios, security_id FK->securities,
         quantity, purchase_price, purchase_date, current_weight, cost_basis,
         UNIQUE(portfolio_id, security_id))

transactions(transaction_id PK, portfolio_id FK->portfolios,
             security_id FK->securities, transaction_type IN ('BUY','SELL'),
             quantity, price, transaction_date, fees, settlement_date, notes)

historical_prices(price_id PK, security_id FK->securities, price_date,
                  open_price, high_price, low_price, close_price, volume,
                  adjusted_close, UNIQUE(security_id, price_date))

portfolio_performance(performance_id PK, portfolio_id FK->portfolios,
                      performance_date, nav, total_return_1m, total_return_3m,
                      total_return_6m, total_return_1y, volatility, sharpe_ratio,
                      max_drawdown, UNIQUE(portfolio_id, performance_date))

risk_metrics(risk_id PK, portfolio_id FK->portfolios, calculation_date,
             var_95, var_99, cvar_95, beta, correlation_sp500, tracking_error,
             information_ratio, sortino_ratio, UNIQUE(portfolio_id, calculation_date))
"""


def _build_system_prompt() -> str:
    return f"""You are a SQL expert for a portfolio management database. 
Generate a single, valid SQLite SELECT query that answers the user's question.

Rules:
- Only output the SQL query, nothing else. No markdown, no explanation, no backticks.
- Use only SELECT or WITH...SELECT statements. Never INSERT, UPDATE, DELETE, DROP.
- Use table aliases for readability.
- Use ROUND() for financial figures to 2 decimal places where appropriate.
- Use COALESCE or NULLIF where division by zero is possible.
- Prefer CTEs (WITH clause) for complex multi-step logic.

{SCHEMA_DESCRIPTION}
"""


def _extract_sql(raw: str) -> str:
    """Strip markdown/code fences and normalize SQL."""
    text = raw.strip()

    # Remove markdown fences
    text = re.sub(r"```(?:sql)?", "", text, flags=re.IGNORECASE)
    text = text.replace("```", "")

    text = text.strip().rstrip(";").strip()

    if not text:
        raise ValueError("Empty SQL generated by model")

    # Ensure it starts with SELECT/WITH
    if not text.lower().startswith(("select", "with")):
        raise ValueError("Model did not return a valid SELECT query")

    return text + ";"


def _validate_sql(sql: str) -> None:
    """Basic safety check: block any non-read statements."""
    upper = sql.upper()
    forbidden = ["INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE", "TRUNCATE"]

    for keyword in forbidden:
        if re.search(rf"\b{keyword}\b", upper):
            raise ValueError(f"Forbidden SQL keyword detected: {keyword}")


class SQLQueryTool:
    def __init__(self, conn: sqlite3.Connection, client: genai.Client, model_name: str):
        self.conn = conn
        self.client = client
        self.model_name = model_name

    def run(self, question: str) -> dict[str, Any]:
        """
        Convert question to SQL, execute it, and return structured result.

        Returns:
            {
                "sql": str,
                "rows": list[dict],
                "row_count": int,
                "columns": list[str],
                "error": str | None
            }
        """
        logger.info("SQLQueryTool received question: %s", question)

        # --- Step 1: Generate SQL ---
        try:
            prompt = f"{_build_system_prompt()}\n\nUser Question:\n{question}"

            response = self.client.models.generate_content(
                model=self.model_name,
                contents=prompt
            )

            raw_sql = response.text

            if not raw_sql:
                raise ValueError("Empty response from model")

        except Exception as exc:
            logger.error("Gemini API error: %s", exc)
            return {
                "sql": None,
                "rows": [],
                "row_count": 0,
                "columns": [],
                "error": f"Model API error: {exc}",
            }

        # --- Step 2: Clean SQL ---
        try:
            sql = _extract_sql(raw_sql)
        except Exception as exc:
            logger.error("SQL extraction error: %s | Raw: %s", exc, raw_sql)
            return {
                "sql": None,
                "rows": [],
                "row_count": 0,
                "columns": [],
                "error": f"SQL extraction error: {exc}",
            }

        logger.info("Generated SQL: %s", sql)

        # --- Step 3: Validate SQL ---
        try:
            _validate_sql(sql)
        except ValueError as exc:
            return {
                "sql": sql,
                "rows": [],
                "row_count": 0,
                "columns": [],
                "error": str(exc),
            }

        # --- Step 4: Execute SQL ---
        try:
            rows = execute_query(self.conn, sql)
            columns = list(rows[0].keys()) if rows else []

            return {
                "sql": sql,
                "rows": rows,
                "row_count": len(rows),
                "columns": columns,
                "error": None,
            }

        except Exception as exc:
            logger.error("SQL execution error: %s | SQL: %s", exc, sql)
            return {
                "sql": sql,
                "rows": [],
                "row_count": 0,
                "columns": [],
                "error": f"SQL execution error: {exc}",
            }